import type { NextPage } from 'next';
import Head from 'next/head';
import LandingPage from '../components/LandingPage';

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Toucan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <LandingPage />
      </main>

    </div>
  )
}

export default Home
