import Head from "next/head";
// import Main from "../components/home";
import Home from "../components/home";

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>DriverClass</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}
