import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from './components/Layout'
import LandingPage from './components/LandingPage';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Toucan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Layout>
          <LandingPage />
        </Layout>
      </main>

    </div>
  )
}

export default Home
